### PR TITLE
Number of updates

### PR DESCRIPTION
**Pull request by tburch-LSS**
--updated to GSL v2.7 (linux *.a files provided; windows libraries will require updating)
--Models moved to Blocks
--many more GSL functions added
--more examples
(sorry for the sudden, massive changes; git newb here)

### CODE REVIEW

**Comment by greenwoodms06** [comment]
This is excellent! I don't see any issue merging your branch.
Before I do though, did you want to update the README.md at all?
- Also, I'm entertaining moving this repo over to ORNL-Modelica - do you have any objections to that? I think it would give it a more "official" presence and perhaps a better place to live-on...

**Comment by tburch-LSS** [comment]
i did update the readme, but not by much. i mainly pointed out the OM / linux compatibility (windows libraries probably need updating and Dymola compatibility remains untested).

entertain away... i may have some updates in the future (more examples, more GSL capabilities)

**Comment by greenwoodms06** [comment]
ok... i'll think about the migration more. i tested it on dymola and i didn't notice any issues). ill update the readme with that info after the merge

**Comment by tburch-LSS** [comment]
great!

**Comment by greenwoodms06** [comment]
@tburch-LSS, let me know if you have any issues with pushing/pulling from the migrated repository so I can fix that ASAP

**Pull request merged**
